name: simple_design
description: The Simple Design library for Flutter. It provides a premade theme for light and dark brightness, aswell as providing alternatives to some material widgets for quick and good design.
version: 1.0.1
author: Leo Dr <leodr.development@gmail.com>
homepage: https://github.com/leodr/simple_design

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: